### ISSUE TITLE
Issue with Synchronous Functions in Asynchronous Environment

### ISSUE THREAD

**Issue by Dorikyh** [ifsvivek/LocalBot#1]
# Issue with Synchronous Functions in Asynchronous Environment
I've noticed that the project is using synchronous functions in several parts of the code. This is problematic because Pycord is an asynchronous library, and using synchronous functions can cause blocking and slowdowns in the bot. This includes using the `requests` module.

## Example
```python
def ollama_chat(prompt, model, system_prompt):
    # Combine the system prompt with the user's prompt
    complete_prompt = system_prompt + "\n" + prompt
    payload = {"prompt": complete_prompt, "model": model, "max_tokens": 150}
    response = requests.post(OLLAMA_API_URL, json=payload)
    response.raise_for_status()
    parts = response.text.strip().split("\n")
    combined_response = ""
    for part in parts:
        json_part = json.loads(part)
        combined_response += json_part.get("response", "")
    return combined_response
```

### Problems in this code
1. **Synchronous Function Declaration**: Declaring the function as synchronous causes the entire program to stop just to execute that function. Since the bot is constantly executing different functions simultaneously, this can lead to significant slowdowns. To avoid this, the function should be defined as asynchronous and called with await.
2. **You are using requests**, this is a **synchronous** module so every request **will stop your bot** completely until the requests is finished, the same thing I said in the first point.

## Suggestions to fix the example
```py
import aiohttp
import asyncio
import json

async def ollama_chat(prompt, model, system_prompt):
    # Combine the system prompt with the user's prompt
    complete_prompt = system_prompt + "\n" + prompt
    payload = {"prompt": complete_prompt, "model": model, "max_tokens": 150}
    
    async with aiohttp.ClientSession() as session:
        async with session.post(OLLAMA_API_URL, json=payload) as response:
            response.raise_for_status()
            text = await response.text()
            parts = text.strip().split("\n")
            combined_response = ""
            for part in parts:
                json_part = json.loads(part)
                combined_response += json_part.get("response", "")
            return combined_response

``` 
Now this function works asynchronously, so you have to call it in this way: await ollama_chat(). This way, the function won't block your bot, allowing many users to execute it and get a response without causing the bot to slow down or shut down.

I also recommend using await ctx.defer() in commands that take a long time to respond. If an interaction (user executing the command) takes more than 5 seconds to respond, it will return Unknown interaction to the user. Using defer, the bot will respond with Bot is thinking, giving it time to execute the command.

In addition, you should completely eliminate the requests module and non-asynchronous functions from the project, and implement asynchronous solutions.

**Comment by Dorikyh** [comment]
If you would like, we can work on fixing this by submitting PRs to address the issue.

**Comment by ifsvivek** [comment]
Thank you for your suggestion. Unfortunately, my hardware is a limiting factor in this situation, so I can't run the bot on multiple servers simultaneously. However, I appreciate your detailed explanation and recommendations regarding the use of asynchronous functions and aiohttp. I'll consider these changes to improve the bot's performance within my current constraints.

**Comment by ifsvivek** [comment]
Thank you for pointing out the issue with using synchronous functions in our asynchronous environment. We appreciate the detailed explanation and the suggestions you provided.

We agree that transitioning to asynchronous functions is crucial for maintaining the performance and responsiveness of our bot. We'll start by creating a PR to refactor the `ollama_chat` function to be asynchronous, as per your recommendations.

We'll also review other parts of the codebase to identify and replace any remaining synchronous functions and eliminate the use of the requests module, ensuring the entire project is fully asynchronous.

Thank you again for your valuable feedback. We look forward to improving the project together.

**Comment by ifsvivek** [comment]
Hey! Thanks for pointing out the issue with the synchronous functions. I really appreciate the detailed explanation and your suggestions.

I totally agree that switching to async functions is important for keeping the bot responsive. So please go ahead and create a PR to refactor the ollama_chat function to make it async, as you recommended.

I’ll also check the rest of the code for any other synchronous functions and remove the requests module to ensure everything is fully async.

Thanks again for your help! Looking forward to making these improvements.

Cheers,
